
language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - npm install -g npm@latest
# adding code to run on powersysterms  
jobs: 
  include:
    - arch: ppc64le
      node_js: 'iojs'
  
